num_parties: 10
partitioning: "iidk"
dirichlet_alpha: 0.5
federated_optimizer: "FedAvg"
epochs: 1
batch_size: 64
client_optimizer: "adam"
model: "resnet56"
data_argu: "no"
comm_round: 100
train_batch_size: 64
learning_rate: 0.001
test_batch_size: 1000
weight_decay: 0.0001
